[package]
name = "rustbot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
poise = "0.6.1"
serenity = "0.12.4"
tokio = {version = "1.45.0", features = ["macros", "rt-multi-thread"] }
